Vagrant.configure(2) do |config|
  # box name
  config.vm.box = "ubuntu/trusty32"

  # Configure VM
  config.vm.provider "virtualbox" do |v|
  ### Change network card to PCnet-FAST III
    # For NAT adapter
    v.customize ["modifyvm", :id, "--nictype1", "Am79C973"]
    # For host-only adapter
    v.customize ["modifyvm", :id, "--nictype2", "Am79C973"]
    v.name = 'RoyalRangersFrontend'
    v.memory = 1024
    v.cpus = 1
  end

  # forward application port
  config.vm.network "forwarded_port", host_ip: "127.0.0.1", guest: 80, host: 9990

  # create private network
  config.vm.network "private_network", ip: "172.16.1.88"

  # share app folder
  config.vm.synced_folder "../../../", "/project"

  # install nginx and dev dependencies
  config.vm.provision "shell", path: "./../../bootstrap.sh"
end